import * as THREE from 'three';
import { CORE_AMBIENT_LIGHT_INTENSITY, CORE_LABEL_REVEAL_ZOOM, CORE_SUN_GLOW_SCALE, CORE_SUN_LIGHT_DISTANCE, CORE_SUN_LIGHT_INTENSITY, CORE_SUN_RADIUS, DEFAULT_CAM_Z, LAYER_BANDS, MAX_GRAPH_ZOOM, MIN_GRAPH_ZOOM, SUN_ANGULAR_SPEED, SUN_ORBIT_RADIUS, SUN_RADIUS_MM, SUN_TRIAD_IDS, TWIN_REST_LEN, TYPE_COLOR } from '../config/KnowledgeUiConfig';

export interface KnowledgeSceneNode { id:string; title:string; type:keyof typeof TYPE_COLOR; status:'pending'|'verified'|'suspended'|'disputed'|'falsified'; mastery:'none'|'touched'|'mastered'; reasoning:string; premises:string[]; logicRuleId?:string; aliases?:string[]; semanticKey?:string; twinGroup?:string; sharedTitle?:string; pos?:THREE.Vector3; vel?:THREE.Vector3; homePos?:THREE.Vector3; layer?:'inner'|'middle'|'outer'|'core'; }
export interface KnowledgeSceneCallbacks { onSelectNode:(id:string)=>void; onOpenPanel:(id:string)=>void; onBackgroundTap:()=>void; onBackgroundDoubleTap:()=>void; }
export interface KnowledgeSceneOptions { host:HTMLElement; labelsLayer:HTMLElement; getNodes:()=>KnowledgeSceneNode[]; callbacks:KnowledgeSceneCallbacks; }
export interface KnowledgeSceneRuntime { markDirty:()=>void; start:()=>void; stop:()=>void; resize:()=>void; setLabelBrightness:(n:number)=>void; setNodeRadius:(n:number)=>void; setHideUntouched:(enabled:boolean)=>void; setCascadeDepthLimit:(n:number|null)=>void; getCameraZ:()=>number; }
type NodeMeshRecord={group:THREE.Group;shell:THREE.Mesh;dot:THREE.Sprite};
type Layer=NonNullable<KnowledgeSceneNode['layer']>;

export function isCoreNodeId(id:string):boolean{return(SUN_TRIAD_IDS as readonly string[]).includes(id);}
export function layerForNode(node:Pick<KnowledgeSceneNode,'id'|'status'|'type'>):Layer{if(isCoreNodeId(node.id))return'core';if(['pending','suspended','disputed'].includes(node.status))return'outer';if(node.type==='axiom'||node.type==='definition'||node.type==='logic-symbol')return'inner';return'middle';}
function hash01(input:string,salt:number){let h=(2166136261^salt)>>>0;for(let i=0;i<input.length;i++){h^=input.charCodeAt(i);h=Math.imul(h,16777619);}h^=h>>>16;h=Math.imul(h,2246822507);h^=h>>>13;return(h>>>0)/4294967296;}
export function initialNodePosition(node:Pick<KnowledgeSceneNode,'id'|'status'|'type'>):THREE.Vector3{const layer=layerForNode(node);if(layer==='core'){const i=Math.max(0,SUN_TRIAD_IDS.indexOf(node.id as (typeof SUN_TRIAD_IDS)[number])),a=i*Math.PI*2/SUN_TRIAD_IDS.length;return new THREE.Vector3(Math.cos(a)*SUN_ORBIT_RADIUS,Math.sin(a)*SUN_ORBIT_RADIUS,0);}const b=LAYER_BANDS[layer],u=hash01(node.id,11),v=hash01(node.id,29),w=hash01(node.id,47),z=1-2*u,phi=Math.PI*2*v,xy=Math.sqrt(Math.max(0,1-z*z)),r=Math.cbrt(b.rMin**3+w*(b.rMax**3-b.rMin**3));return new THREE.Vector3(r*xy*Math.cos(phi),r*xy*Math.sin(phi),r*z);}
export function shouldRenderEdge(fromId:string,toId:string){return!isCoreNodeId(fromId)&&!isCoreNodeId(toId);}
export function clampGraphZoom(z:number){return THREE.MathUtils.clamp(z,MIN_GRAPH_ZOOM,MAX_GRAPH_ZOOM);}
export function ordinaryNodeCompensationScale(graphZoom:number){return 1/clampGraphZoom(graphZoom);}
export function nodeRadiusForType(type:KnowledgeSceneNode['type'],conclusionRadius:number){return type==='reasoning'?conclusionRadius/3:conclusionRadius;}
export function coreLabelsVisible(graphZoom:number){return graphZoom>=CORE_LABEL_REVEAL_ZOOM;}
export function coreSunContainsTriad(){return CORE_SUN_RADIUS>SUN_ORBIT_RADIUS+SUN_RADIUS_MM;}
export function coreOrbitScreenPosition(index:number,angle:number){const a=angle+index*Math.PI*2/SUN_TRIAD_IDS.length;return new THREE.Vector3(Math.cos(a)*SUN_ORBIT_RADIUS,Math.sin(a)*SUN_ORBIT_RADIUS,0);}

export function createKnowledgeScene({host,labelsLayer,getNodes,callbacks}:KnowledgeSceneOptions):KnowledgeSceneRuntime{
 let running=false,rafId=0,labelBrightness=1,nodeRadiusMM=9,hideUntouched=false,selectedId:string|null=null,draggedNodeId:string|null=null,graphZoom=1;
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(50,host.clientWidth/Math.max(host.clientHeight,1),.5,8000);camera.position.set(0,0,DEFAULT_CAM_Z);
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);host.appendChild(renderer.domElement);
 const worldGroup=new THREE.Group(),edgesGroup=new THREE.Group(),nodesGroup=new THREE.Group();scene.add(worldGroup);worldGroup.add(edgesGroup,nodesGroup);
 scene.add(new THREE.AmbientLight(0xffffff,CORE_AMBIENT_LIGHT_INTENSITY));
 const starVerts:number[]=[];for(let i=0;i<500;i++)starVerts.push((Math.random()-.5)*1800,(Math.random()-.5)*1200,-900-Math.random()*1200);const starGeo=new THREE.BufferGeometry();starGeo.setAttribute('position',new THREE.Float32BufferAttribute(starVerts,3));scene.add(new THREE.Points(starGeo,new THREE.PointsMaterial({color:0xb8bfd4,size:1.2,transparent:true,opacity:.45})));
 const glow=(strong:boolean)=>{const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d')!,g=x.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(strong?.45:.28,strong?'rgba(255,225,150,.72)':'rgba(120,240,220,.55)');g.addColorStop(1,'rgba(95,209,201,0)');x.fillStyle=g;x.fillRect(0,0,128,128);return new THREE.CanvasTexture(c);};
 const strongTex=glow(true),fluorTex=glow(false);
 const coreSunGroup=new THREE.Group();coreSunGroup.position.set(0,0,0);worldGroup.add(coreSunGroup);
 const coreSun=new THREE.Mesh(new THREE.SphereGeometry(CORE_SUN_RADIUS,32,20),new THREE.MeshBasicMaterial({color:0xffd978,transparent:true,opacity:.32,depthTest:false,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending}));coreSun.renderOrder=10;coreSunGroup.add(coreSun);
 const coreSunGlow=new THREE.Sprite(new THREE.SpriteMaterial({map:strongTex,color:0xffd978,transparent:true,opacity:.62,depthTest:false,depthWrite:false,blending:THREE.AdditiveBlending}));coreSunGlow.scale.setScalar(CORE_SUN_RADIUS*2*CORE_SUN_GLOW_SCALE);coreSunGlow.renderOrder=9;coreSunGroup.add(coreSunGlow);
 const coreLight=new THREE.PointLight(0xffd98a,CORE_SUN_LIGHT_INTENSITY,CORE_SUN_LIGHT_DISTANCE,2);coreLight.position.set(0,0,0);coreSunGroup.add(coreLight);
 const nodeMap:Record<string,NodeMeshRecord>={},edgeMap:Record<string,THREE.Line>={},labelMap:Record<string,HTMLDivElement>={};
 const pointers=new Map<number,{x:number;y:number}>();let mode:'rotate'|'node'|'pinch'|null=null,pinchOccurred=false,downX=0,downY=0,lastX=0,lastY=0,pinchStartDist=0,pinchStartZoom=1,lastBgTapTime=0,bgTapTimer:number|null=null;
 const clock=new THREE.Clock(),raycaster=new THREE.Raycaster(),ndc=new THREE.Vector2(),scratch=new THREE.Vector3(),worldPos=new THREE.Vector3();
 const place=(n:KnowledgeSceneNode)=>{n.layer=layerForNode(n);n.pos=initialNodePosition(n);n.vel=new THREE.Vector3();n.homePos=n.pos.clone();};
 const ensure=(n:KnowledgeSceneNode)=>{if(nodeMap[n.id])return nodeMap[n.id];const core=isCoreNodeId(n.id),group=new THREE.Group();group.userData.nodeId=n.id;const shellMaterial=new THREE.MeshPhongMaterial({color:TYPE_COLOR[n.type],emissive:TYPE_COLOR[n.type],emissiveIntensity:core?.32:.08,shininess:55,wireframe:true,transparent:true,opacity:core?.72:.5,depthTest:!core,depthWrite:!core});const shell=new THREE.Mesh(new THREE.SphereGeometry(1,24,12),shellMaterial);shell.renderOrder=core?20:0;const dot=new THREE.Sprite(new THREE.SpriteMaterial({map:fluorTex,transparent:true,opacity:.9,depthTest:!core,depthWrite:false}));dot.renderOrder=core?21:1;group.add(shell,dot);nodesGroup.add(group);const label=document.createElement('div');label.className='node-label';label.textContent=n.title;labelsLayer.appendChild(label);labelMap[n.id]=label;return nodeMap[n.id]={group,shell,dot};};
 const updateLine=(l:THREE.Line,a?:THREE.Vector3,b?:THREE.Vector3)=>{if(!a||!b)return;l.geometry.dispose();l.geometry=new THREE.BufferGeometry().setFromPoints([a.clone(),b.clone()]);if('computeLineDistances'in l)l.computeLineDistances();};
 const syncEdges=(nodes:KnowledgeSceneNode[])=>{const ids=new Set(nodes.map(n=>n.id)),wanted=new Set<string>();nodes.forEach(n=>[...n.premises,...(n.logicRuleId?[n.logicRuleId]:[])].forEach(p=>{if(!ids.has(p)||!shouldRenderEdge(p,n.id))return;const k=`${p}->${n.id}`;wanted.add(k);if(!edgeMap[k]){edgeMap[k]=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:n.logicRuleId===p?0xa6e3a1:0x7c93c9,transparent:true,opacity:.32}));edgesGroup.add(edgeMap[k]);}updateLine(edgeMap[k],nodeMap[p]?.group.position,nodeMap[n.id]?.group.position);}));nodes.filter(n=>n.twinGroup&&!isCoreNodeId(n.id)).forEach(n=>{const t=nodes.find(o=>o.id!==n.id&&o.twinGroup===n.twinGroup&&shouldRenderEdge(n.id,o.id));if(!t)return;const k=[n.id,t.id].sort().join('<->');wanted.add(k);if(!edgeMap[k]){edgeMap[k]=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:0xffd978,transparent:true,opacity:.5,dashSize:4,gapSize:3}));edgesGroup.add(edgeMap[k]);}updateLine(edgeMap[k],nodeMap[n.id]?.group.position,nodeMap[t.id]?.group.position);});Object.keys(edgeMap).forEach(k=>{if(!wanted.has(k)){edgesGroup.remove(edgeMap[k]);edgeMap[k].geometry.dispose();delete edgeMap[k];}});};
 const applyVisibility=()=>getNodes().forEach(n=>{const visible=isCoreNodeId(n.id)||!hideUntouched||n.mastery!=='none';if(nodeMap[n.id])nodeMap[n.id].group.visible=visible;if(labelMap[n.id])labelMap[n.id].style.display=visible?'':'none';});
 const sync=()=>{worldGroup.scale.setScalar(graphZoom);const nodes=getNodes(),ids=new Set(nodes.map(n=>n.id));Object.keys(nodeMap).forEach(id=>{if(!ids.has(id)){nodesGroup.remove(nodeMap[id].group);labelMap[id]?.remove();delete nodeMap[id];delete labelMap[id];}});nodes.forEach(n=>{if(!n.pos)place(n);const r=ensure(n);r.group.position.copy(n.pos!);const core=isCoreNodeId(n.id),radius=core?SUN_RADIUS_MM:nodeRadiusForType(n.type,nodeRadiusMM);r.shell.scale.setScalar(radius*(core?1:ordinaryNodeCompensationScale(graphZoom)));r.dot.scale.setScalar((n.mastery==='mastered'?radius*3:n.mastery==='touched'?radius*2.2:.01)*(core?1:ordinaryNodeCompensationScale(graphZoom)));(r.dot.material as THREE.SpriteMaterial).map=n.mastery==='mastered'?strongTex:fluorTex;(r.shell.material as THREE.MeshPhongMaterial).color.setHex(TYPE_COLOR[n.type]);(r.shell.material as THREE.MeshPhongMaterial).emissive.setHex(TYPE_COLOR[n.type]);});syncEdges(nodes);applyVisibility();};
 const physics=(dt:number)=>{const nodes=getNodes(),inverseWorldRotation=worldGroup.quaternion.clone().invert();nodes.forEach(n=>{if(!n.pos)place(n);if(draggedNodeId===n.id)return;if(isCoreNodeId(n.id)){const i=SUN_TRIAD_IDS.indexOf(n.id as (typeof SUN_TRIAD_IDS)[number]),screenOrbit=coreOrbitScreenPosition(i,clock.elapsedTime*SUN_ANGULAR_SPEED);n.pos!.copy(screenOrbit.applyQuaternion(inverseWorldRotation));return;}n.vel??=new THREE.Vector3();n.homePos??=n.pos!.clone();n.vel.add(scratch.copy(n.homePos).sub(n.pos!).multiplyScalar(.02));nodes.forEach(o=>{if(o===n||!o.pos||isCoreNodeId(o.id))return;const d=scratch.copy(n.pos!).sub(o.pos),d2=Math.max(d.lengthSq(),80);n.vel!.add(d.normalize().multiplyScalar(12/d2));});[...n.premises,...(n.logicRuleId?[n.logicRuleId]:[])].forEach(pid=>{const p=nodes.find(o=>o.id===pid&&!isCoreNodeId(o.id)&&o.pos);if(p?.pos){const d=scratch.copy(p.pos).sub(n.pos!),len=d.length();if(len>0)n.vel!.add(d.normalize().multiplyScalar((len-TWIN_REST_LEN)*.0015));}});if(n.twinGroup){const t=nodes.find(o=>o!==n&&o.twinGroup===n.twinGroup&&o.pos);if(t?.pos){const d=scratch.copy(t.pos).sub(n.pos!);n.vel.add(d.multiplyScalar((d.length()-TWIN_REST_LEN)*.002));}}n.vel.multiplyScalar(.88);n.pos!.addScaledVector(n.vel,dt*60);});};
 const labels=()=>{scene.updateMatrixWorld(true);getNodes().forEach(n=>{const l=labelMap[n.id],r=nodeMap[n.id];if(!l||!r)return;r.group.getWorldPosition(worldPos);const s=worldPos.clone().project(camera),visible=r.group.visible&&s.z>-1&&s.z<1&&(!isCoreNodeId(n.id)||coreLabelsVisible(graphZoom));l.style.display=visible?'':'none';if(!visible)return;l.style.transform=`translate(-50%, -50%) translate(${(s.x*.5+.5)*host.clientWidth}px, ${(-s.y*.5+.5)*host.clientHeight}px)`;l.style.opacity=String(labelBrightness);l.classList.toggle('selected',selectedId===n.id);});};
 const pick=(x:number,y:number)=>{const rect=renderer.domElement.getBoundingClientRect();ndc.set(((x-rect.left)/rect.width)*2-1,-(((y-rect.top)/rect.height)*2-1));raycaster.setFromCamera(ndc,camera);const hit=raycaster.intersectObjects(Object.values(nodeMap).filter(r=>r.group.visible).map(r=>r.shell),false)[0]?.object.parent?.userData.nodeId;return typeof hit==='string'?hit:null;};
 const down=(e:PointerEvent)=>{renderer.domElement.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});downX=lastX=e.clientX;downY=lastY=e.clientY;if(pointers.size===2){const[a,b]=[...pointers.values()];pinchStartDist=Math.hypot(a.x-b.x,a.y-b.y);pinchStartZoom=graphZoom;pinchOccurred=true;mode='pinch';return;}draggedNodeId=pick(e.clientX,e.clientY);mode=draggedNodeId?'node':'rotate';};
 const move=(e:PointerEvent)=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(mode==='pinch'&&pointers.size>=2){const[a,b]=[...pointers.values()],dist=Math.max(Math.hypot(a.x-b.x,a.y-b.y),1);graphZoom=clampGraphZoom(pinchStartZoom*dist/pinchStartDist);}else if(mode==='rotate'){worldGroup.rotation.y+=(e.clientX-lastX)*.004;worldGroup.rotation.x+=(e.clientY-lastY)*.004;}else if(mode==='node'&&draggedNodeId){const n=getNodes().find(v=>v.id===draggedNodeId);if(n?.pos){const d=new THREE.Vector3((e.clientX-lastX)*.45/graphZoom,-(e.clientY-lastY)*.45/graphZoom,0).applyQuaternion(worldGroup.quaternion.clone().invert());n.pos.add(d);}}lastX=e.clientX;lastY=e.clientY;};
 const up=(e:PointerEvent)=>{pointers.delete(e.pointerId);const moved=Math.hypot(e.clientX-downX,e.clientY-downY)>6,nodeId=!moved&&!pinchOccurred?pick(e.clientX,e.clientY):null;if(nodeId){selectedId=nodeId;callbacks.onSelectNode(nodeId);callbacks.onOpenPanel(nodeId);}else if(!moved&&!pinchOccurred){const now=performance.now();if(now-lastBgTapTime<280){if(bgTapTimer!==null)clearTimeout(bgTapTimer);bgTapTimer=null;callbacks.onBackgroundDoubleTap();}else bgTapTimer=window.setTimeout(()=>callbacks.onBackgroundTap(),280);lastBgTapTime=now;}if(pointers.size===0){mode=null;draggedNodeId=null;pinchOccurred=false;}};
 const wheel=(e:WheelEvent)=>{e.preventDefault();graphZoom=clampGraphZoom(graphZoom*Math.exp(-e.deltaY*.0015));};
 const resize=()=>{camera.aspect=host.clientWidth/Math.max(host.clientHeight,1);camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight);document.documentElement.style.setProperty('--app-height',`${window.innerHeight}px`);};
 const frame=()=>{if(!running)return;const dt=Math.min(clock.getDelta(),.05);sync();physics(dt);sync();labels();renderer.render(scene,camera);rafId=requestAnimationFrame(frame);};
 renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',up);renderer.domElement.addEventListener('wheel',wheel,{passive:false});resize();
 return{markDirty:()=>{},start:()=>{if(!running){running=true;clock.start();frame();}},stop:()=>{running=false;cancelAnimationFrame(rafId);},resize,setLabelBrightness:n=>{labelBrightness=THREE.MathUtils.clamp(n,.1,1);},setNodeRadius:n=>{nodeRadiusMM=THREE.MathUtils.clamp(n,.1,30);},setHideUntouched:e=>{hideUntouched=e;applyVisibility();},setCascadeDepthLimit:()=>{},getCameraZ:()=>camera.position.z};
}
