import * as THREE from 'three';
import { CORE_AMBIENT_LIGHT_INTENSITY, CORE_LABEL_REVEAL_ZOOM, CORE_SUN_COLOR, CORE_SUN_GLOW_SCALE, CORE_SUN_LIGHT_DECAY, CORE_SUN_LIGHT_DISTANCE, CORE_SUN_LIGHT_INTENSITY, CORE_SUN_RADIUS, CORE_SUN_SHADOW_FAR, DEFAULT_CAM_Z, KNOWLEDGE_SCENE_THEME, LAYER_BANDS, MAX_GRAPH_ZOOM, MIN_GRAPH_ZOOM, NODE_LAYER_COLOR, NODE_SPECIAL_COLOR, PENDING_PULSE_FADE_MS, PENDING_PULSE_LOW_MS, PENDING_PULSE_MIN_OPACITY, PENDING_PULSE_MIN_SCALE, PENDING_PULSE_PERIOD_MS, PENDING_PULSE_RISE_MS, PENDING_PULSE_VISIBLE_MS, SUN_ANGULAR_SPEED, SUN_ORBIT_RADIUS, SUN_RADIUS_MM, SUN_TRIAD_IDS, TWIN_REST_LEN, TYPE_COLOR } from '../config/KnowledgeUiConfig';

export interface KnowledgeSceneNode { id:string; title:string; type:keyof typeof TYPE_COLOR; status:'pending'|'verified'|'suspended'|'disputed'|'falsified'; mastery:'none'|'touched'|'mastered'; reasoning:string; premises:string[]; logicRuleId?:string; aliases?:string[]; semanticKey?:string; twinGroup?:string; sharedTitle?:string; pos?:THREE.Vector3; vel?:THREE.Vector3; homePos?:THREE.Vector3; layer?:'inner'|'middle'|'outer'|'core'; }
export interface KnowledgeSceneCallbacks { onNodeTap:(id:string)=>void; onBackgroundTap:()=>void; onBackgroundDoubleTap:()=>void; }
export interface KnowledgeSceneOptions { host:HTMLElement; labelsLayer:HTMLElement; getNodes:()=>KnowledgeSceneNode[]; callbacks:KnowledgeSceneCallbacks; }
export interface KnowledgeSceneRuntime { markDirty:()=>void; start:()=>void; stop:()=>void; setOverlayVisible:(visible:boolean)=>void; resize:()=>void; setLabelBrightness:(n:number)=>void; setNodeRadius:(n:number)=>void; setHideUntouched:(enabled:boolean)=>void; setCascadeDepthLimit:(n:number|null)=>void; getCameraZ:()=>number; screenPositionForNode:(id:string)=>{x:number;y:number}|null; }
type NodeMeshRecord={group:THREE.Group;shell:THREE.Mesh;point:THREE.Sprite;dot:THREE.Sprite;baseShellOpacity:number;basePointOpacity:number;baseDotOpacity:number};
type Layer=NonNullable<KnowledgeSceneNode['layer']>;

export function isCoreNodeId(id:string):boolean{return(SUN_TRIAD_IDS as readonly string[]).includes(id);}
export function layerForNode(node:Pick<KnowledgeSceneNode,'id'|'status'|'type'>):Layer{if(isCoreNodeId(node.id))return'core';if(['pending','suspended','disputed'].includes(node.status))return'outer';if(node.type==='axiom'||node.type==='definition'||node.type==='logic-symbol')return'inner';return'middle';}
export function colorForNode(node:Pick<KnowledgeSceneNode,'id'|'status'|'type'>):number{if(node.status==='falsified')return NODE_SPECIAL_COLOR.falsified;if(node.type==='reasoning'||node.type==='logic-symbol')return NODE_SPECIAL_COLOR.structural;return NODE_LAYER_COLOR[layerForNode(node)];}
function hash01(input:string,salt:number){let h=(2166136261^salt)>>>0;for(let i=0;i<input.length;i++){h^=input.charCodeAt(i);h=Math.imul(h,16777619);}h^=h>>>16;h=Math.imul(h,2246822507);h^=h>>>13;return(h>>>0)/4294967296;}
function smoothStep01(value:number){const t=THREE.MathUtils.clamp(value,0,1);return t*t*(3-2*t);}
export function pendingPulseAtCycleMs(cycleMs:number):{opacityFactor:number;scale:number}{const t=((cycleMs%PENDING_PULSE_PERIOD_MS)+PENDING_PULSE_PERIOD_MS)%PENDING_PULSE_PERIOD_MS,fadeStart=PENDING_PULSE_VISIBLE_MS,lowStart=fadeStart+PENDING_PULSE_FADE_MS,riseStart=lowStart+PENDING_PULSE_LOW_MS;if(t<fadeStart)return{opacityFactor:1,scale:1};if(t<lowStart){const p=smoothStep01((t-fadeStart)/PENDING_PULSE_FADE_MS);return{opacityFactor:THREE.MathUtils.lerp(1,PENDING_PULSE_MIN_OPACITY,p),scale:THREE.MathUtils.lerp(1,PENDING_PULSE_MIN_SCALE,p)};}if(t<riseStart)return{opacityFactor:PENDING_PULSE_MIN_OPACITY,scale:PENDING_PULSE_MIN_SCALE};const p=smoothStep01((t-riseStart)/PENDING_PULSE_RISE_MS);return{opacityFactor:THREE.MathUtils.lerp(PENDING_PULSE_MIN_OPACITY,1,p),scale:THREE.MathUtils.lerp(PENDING_PULSE_MIN_SCALE,1,p)};}
export function pendingPulsePhaseMs(nodeId:string):number{return hash01(nodeId,83)*PENDING_PULSE_PERIOD_MS;}
export function pendingPulseState(nodeId:string,timeMs:number){return pendingPulseAtCycleMs(timeMs+pendingPulsePhaseMs(nodeId));}
export function initialNodePosition(node:Pick<KnowledgeSceneNode,'id'|'status'|'type'>):THREE.Vector3{const layer=layerForNode(node);if(layer==='core'){const i=Math.max(0,SUN_TRIAD_IDS.indexOf(node.id as (typeof SUN_TRIAD_IDS)[number])),a=i*Math.PI*2/SUN_TRIAD_IDS.length;return new THREE.Vector3(Math.cos(a)*SUN_ORBIT_RADIUS,Math.sin(a)*SUN_ORBIT_RADIUS,0);}const b=LAYER_BANDS[layer],u=hash01(node.id,11),v=hash01(node.id,29),w=hash01(node.id,47),z=1-2*u,phi=Math.PI*2*v,xy=Math.sqrt(Math.max(0,1-z*z)),r=Math.cbrt(b.rMin**3+w*(b.rMax**3-b.rMin**3));return new THREE.Vector3(r*xy*Math.cos(phi),r*xy*Math.sin(phi),r*z);}
export function shouldRenderEdge(fromId:string,toId:string){return!isCoreNodeId(fromId)&&!isCoreNodeId(toId);}
export function clampGraphZoom(z:number){return THREE.MathUtils.clamp(z,MIN_GRAPH_ZOOM,MAX_GRAPH_ZOOM);}
export function ordinaryNodeCompensationScale(graphZoom:number){return 1/clampGraphZoom(graphZoom);}
export function nodeRadiusForType(type:KnowledgeSceneNode['type'],conclusionRadius:number){return type==='reasoning'?conclusionRadius/3:conclusionRadius;}
export function coreLabelsVisible(graphZoom:number){return graphZoom>=CORE_LABEL_REVEAL_ZOOM;}
export function coreSunContainsTriad(){return CORE_SUN_RADIUS>SUN_ORBIT_RADIUS+SUN_RADIUS_MM;}
export function coreOrbitScreenPosition(index:number,angle:number){const a=angle+index*Math.PI*2/SUN_TRIAD_IDS.length;return new THREE.Vector3(Math.cos(a)*SUN_ORBIT_RADIUS,Math.sin(a)*SUN_ORBIT_RADIUS,0);}
export function hasFiniteCoordinates(vector:Pick<THREE.Vector3,'x'|'y'|'z'>|undefined):boolean{return Boolean(vector&&[vector.x,vector.y,vector.z].every(Number.isFinite));}
export function createCoreSunLight(){const light=new THREE.PointLight(CORE_SUN_COLOR,CORE_SUN_LIGHT_INTENSITY,CORE_SUN_LIGHT_DISTANCE,CORE_SUN_LIGHT_DECAY);light.position.set(0,0,0);light.castShadow=true;light.shadow.mapSize.set(512,512);light.shadow.camera.near=.5;light.shadow.camera.far=CORE_SUN_SHADOW_FAR;light.shadow.camera.updateProjectionMatrix();return light;}

export function createKnowledgeScene({host,labelsLayer,getNodes,callbacks}:KnowledgeSceneOptions):KnowledgeSceneRuntime{
 let running=false,overlayVisible=false,largeGraphDirty=true,rafId=0,frameTimer:number|null=null,labelBrightness=1,nodeRadiusMM=7.2,hideUntouched=false,selectedId:string|null=null,draggedNodeId:string|null=null,graphZoom=1.27,lastFrameAt=0;const mobilePerformance=window.matchMedia('(max-width: 640px)').matches;
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(50,host.clientWidth/Math.max(host.clientHeight,1),.5,8000);camera.position.set(0,0,DEFAULT_CAM_Z);
 const renderer=new THREE.WebGLRenderer({antialias:!mobilePerformance,alpha:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,mobilePerformance?1:2));renderer.setSize(host.clientWidth,host.clientHeight);renderer.setClearColor(0x000000,0);renderer.shadowMap.enabled=!mobilePerformance;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.domElement.style.touchAction='none';host.appendChild(renderer.domElement);
 const worldGroup=new THREE.Group(),edgesGroup=new THREE.Group(),nodesGroup=new THREE.Group();scene.add(worldGroup);worldGroup.add(edgesGroup,nodesGroup);
 scene.add(new THREE.AmbientLight(0xffffff,CORE_AMBIENT_LIGHT_INTENSITY));
 const glow=(strong:boolean)=>{const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d')!,g=x.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,KNOWLEDGE_SCENE_THEME.mastery.coreStop);g.addColorStop(strong?.46:.34,strong?KNOWLEDGE_SCENE_THEME.mastery.masteredMidStop:KNOWLEDGE_SCENE_THEME.mastery.touchedMidStop);g.addColorStop(1,KNOWLEDGE_SCENE_THEME.mastery.edgeStop);x.fillStyle=g;x.fillRect(0,0,128,128);return new THREE.CanvasTexture(c);};
 const strongTex=glow(true),fluorTex=glow(false);
 const coreSunGroup=new THREE.Group();coreSunGroup.position.set(0,0,0);worldGroup.add(coreSunGroup);
 const coreSun=new THREE.Mesh(new THREE.SphereGeometry(CORE_SUN_RADIUS,32,20),new THREE.MeshPhongMaterial({color:CORE_SUN_COLOR,emissive:CORE_SUN_COLOR,emissiveIntensity:.82,transparent:true,opacity:KNOWLEDGE_SCENE_THEME.sun.coreOpacity,depthTest:true,depthWrite:false}));coreSun.renderOrder=12;coreSunGroup.add(coreSun);
 const coreSunInnerGlow=new THREE.Sprite(new THREE.SpriteMaterial({map:strongTex,color:KNOWLEDGE_SCENE_THEME.sun.core,transparent:true,opacity:KNOWLEDGE_SCENE_THEME.sun.innerGlowOpacity,depthTest:true,depthWrite:false}));coreSunInnerGlow.scale.setScalar(CORE_SUN_RADIUS*2*KNOWLEDGE_SCENE_THEME.sun.innerGlowScale);coreSunInnerGlow.renderOrder=11;coreSunGroup.add(coreSunInnerGlow);
 const coreSunCorona=new THREE.Sprite(new THREE.SpriteMaterial({map:strongTex,color:KNOWLEDGE_SCENE_THEME.sun.corona,transparent:true,opacity:KNOWLEDGE_SCENE_THEME.sun.coronaOpacity,depthTest:true,depthWrite:false}));coreSunCorona.scale.setScalar(CORE_SUN_RADIUS*2*CORE_SUN_GLOW_SCALE);coreSunCorona.renderOrder=10;coreSunGroup.add(coreSunCorona);
 const coreSunHalo=new THREE.Sprite(new THREE.SpriteMaterial({map:strongTex,color:KNOWLEDGE_SCENE_THEME.sun.halo,transparent:true,opacity:KNOWLEDGE_SCENE_THEME.sun.haloOpacity,depthTest:true,depthWrite:false}));coreSunHalo.scale.setScalar(CORE_SUN_RADIUS*2*KNOWLEDGE_SCENE_THEME.sun.haloScale);coreSunHalo.renderOrder=9;coreSunGroup.add(coreSunHalo);
 const coreLight=createCoreSunLight();coreLight.castShadow=!mobilePerformance;coreSunGroup.add(coreLight);
 const nodeMap:Record<string,NodeMeshRecord>={},edgeMap:Record<string,THREE.Line>={},labelMap:Record<string,HTMLDivElement>={},pendingNodeIds=new Set<string>();
 const pointers=new Map<number,{x:number;y:number}>();let mode:'rotate'|'node'|'pinch'|null=null,pinchOccurred=false,downX=0,downY=0,lastX=0,lastY=0,pinchStartDist=0,pinchStartZoom=1,lastBgTapTime=0,bgTapTimer:number|null=null;
 const clock=new THREE.Clock(),raycaster=new THREE.Raycaster(),ndc=new THREE.Vector2(),scratch=new THREE.Vector3(),worldPos=new THREE.Vector3();let lastEdgeSync=0;
 const place=(n:KnowledgeSceneNode)=>{n.layer=layerForNode(n);n.pos=initialNodePosition(n);n.vel=new THREE.Vector3();n.homePos=n.pos.clone();};
 const colorFor=(n:KnowledgeSceneNode)=>colorForNode(n);
 const masteryOpacity=(n:KnowledgeSceneNode)=>n.mastery==='mastered'?KNOWLEDGE_SCENE_THEME.mastery.masteredOpacity:n.mastery==='touched'?KNOWLEDGE_SCENE_THEME.mastery.touchedOpacity:KNOWLEDGE_SCENE_THEME.mastery.noneOpacity;
 const ensure=(n:KnowledgeSceneNode)=>{if(nodeMap[n.id])return nodeMap[n.id];const core=isCoreNodeId(n.id),color=colorFor(n),group=new THREE.Group();group.userData.nodeId=n.id;const shellMaterial=new THREE.MeshPhongMaterial({color,emissive:color,emissiveIntensity:core?.34:KNOWLEDGE_SCENE_THEME.node.baseEmissiveIntensity,shininess:42,wireframe:false,transparent:true,opacity:core?.84:KNOWLEDGE_SCENE_THEME.node.shellOpacity,depthTest:!core,depthWrite:!core});const shell=new THREE.Mesh(new THREE.SphereGeometry(1,24,12),shellMaterial);shell.renderOrder=core?20:0;shell.castShadow=!mobilePerformance;shell.receiveShadow=!mobilePerformance;const pointMaterial=new THREE.SpriteMaterial({map:fluorTex,color,transparent:true,opacity:KNOWLEDGE_SCENE_THEME.node.pointOpacity,depthTest:!core,depthWrite:false}),point=new THREE.Sprite(pointMaterial);point.renderOrder=core?21:1;const dotMaterial=new THREE.SpriteMaterial({map:n.mastery==='mastered'?strongTex:fluorTex,color:KNOWLEDGE_SCENE_THEME.mastery.tint,transparent:true,opacity:masteryOpacity(n),depthTest:!core,depthWrite:false}),dot=new THREE.Sprite(dotMaterial);dot.renderOrder=core?22:2;group.add(shell,point,dot);nodesGroup.add(group);const label=document.createElement('div');label.className='node-label';label.textContent=n.title;labelsLayer.appendChild(label);labelMap[n.id]=label;return nodeMap[n.id]={group,shell,point,dot,baseShellOpacity:shellMaterial.opacity,basePointOpacity:pointMaterial.opacity,baseDotOpacity:dotMaterial.opacity};};
 const updateLine=(l:THREE.Line,a?:THREE.Vector3,b?:THREE.Vector3)=>{if(!hasFiniteCoordinates(a)||!hasFiniteCoordinates(b)){l.visible=false;return;}const midpoint=a!.clone().add(b!).multiplyScalar(.5),distance=a!.distanceTo(b!);if(!Number.isFinite(distance)){l.visible=false;return;}const delta=b!.clone().sub(a!),bend=delta.lengthSq()>1e-12?new THREE.Vector3(-delta.y,delta.x,0).normalize().multiplyScalar(Math.min(distance*.07,8)):new THREE.Vector3();midpoint.add(bend);const points=new THREE.QuadraticBezierCurve3(a!.clone(),midpoint,b!.clone()).getPoints(18);if(points.some(point=>!hasFiniteCoordinates(point))){l.visible=false;return;}l.geometry.setFromPoints(points);l.visible=true;if(l.material instanceof THREE.LineDashedMaterial)l.computeLineDistances();};
 const syncEdges=(nodes:KnowledgeSceneNode[])=>{const ids=new Set(nodes.map(n=>n.id)),wanted=new Set<string>(),hasSelection=selectedId!==null;nodes.forEach(n=>[...n.premises,...(n.logicRuleId?[n.logicRuleId]:[])].forEach(p=>{if(!ids.has(p)||!shouldRenderEdge(p,n.id))return;const k=`${p}->${n.id}`,logic=n.logicRuleId===p;wanted.add(k);if(!edgeMap[k]){edgeMap[k]=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:logic?KNOWLEDGE_SCENE_THEME.edge.logic:KNOWLEDGE_SCENE_THEME.edge.normal,transparent:true,opacity:KNOWLEDGE_SCENE_THEME.edge.normalOpacity}));edgesGroup.add(edgeMap[k]);}const material=edgeMap[k].material as THREE.LineBasicMaterial;material.color.setHex(logic?KNOWLEDGE_SCENE_THEME.edge.logic:KNOWLEDGE_SCENE_THEME.edge.normal);const relationActive=hasSelection&&(selectedId===p||selectedId===n.id||n.premises.includes(selectedId!));const stateOpacity=n.status==='falsified'?KNOWLEDGE_SCENE_THEME.edge.falsifiedOpacity:n.status==='suspended'?KNOWLEDGE_SCENE_THEME.edge.suspendedOpacity:n.status==='disputed'?KNOWLEDGE_SCENE_THEME.edge.disputedOpacity:KNOWLEDGE_SCENE_THEME.edge.normalOpacity;material.opacity=relationActive?KNOWLEDGE_SCENE_THEME.edge.activeOpacity:stateOpacity*(hasSelection?KNOWLEDGE_SCENE_THEME.edge.inactiveFactor:1);updateLine(edgeMap[k],nodeMap[p]?.group.position,nodeMap[n.id]?.group.position);}));nodes.filter(n=>n.twinGroup&&!isCoreNodeId(n.id)).forEach(n=>{const t=nodes.find(o=>o.id!==n.id&&o.twinGroup===n.twinGroup&&shouldRenderEdge(n.id,o.id));if(!t)return;const k=[n.id,t.id].sort().join('<->');wanted.add(k);if(!edgeMap[k]){edgeMap[k]=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:KNOWLEDGE_SCENE_THEME.edge.twin,transparent:true,opacity:KNOWLEDGE_SCENE_THEME.edge.twinOpacity,dashSize:4,gapSize:3}));edgesGroup.add(edgeMap[k]);}const material=edgeMap[k].material as THREE.LineDashedMaterial;material.color.setHex(KNOWLEDGE_SCENE_THEME.edge.twin);material.opacity=KNOWLEDGE_SCENE_THEME.edge.twinOpacity;updateLine(edgeMap[k],nodeMap[n.id]?.group.position,nodeMap[t.id]?.group.position);});Object.keys(edgeMap).forEach(k=>{if(!wanted.has(k)){edgesGroup.remove(edgeMap[k]);edgeMap[k].geometry.dispose();delete edgeMap[k];}});};
 const applyVisibility=()=>getNodes().forEach(n=>{const visible=isCoreNodeId(n.id)||!hideUntouched||n.mastery!=='none';if(nodeMap[n.id])nodeMap[n.id].group.visible=visible;if(labelMap[n.id])labelMap[n.id].style.display=visible?'':'none';});
 const sync=()=>{worldGroup.scale.setScalar(graphZoom);const nodes=getNodes(),largeMobileGraph=mobilePerformance&&nodes.length>200,ids=new Set(nodes.map(n=>n.id)),byId=new Map(nodes.map(n=>[n.id,n]));pendingNodeIds.clear();Object.keys(nodeMap).forEach(id=>{if(!ids.has(id)){nodesGroup.remove(nodeMap[id].group);labelMap[id]?.remove();delete nodeMap[id];delete labelMap[id];}});nodes.forEach(n=>{if(!hasFiniteCoordinates(n.pos))place(n);const r=ensure(n);r.group.position.copy(n.pos!);r.group.scale.setScalar(1);const core=isCoreNodeId(n.id),pending=!core&&n.status==='pending',radius=core?SUN_RADIUS_MM:nodeRadiusForType(n.type,nodeRadiusMM),color=colorFor(n),comp=core?1:ordinaryNodeCompensationScale(graphZoom);if(pending)pendingNodeIds.add(n.id);r.shell.visible=!largeMobileGraph||core||pending||selectedId===n.id;r.point.visible=!core;r.shell.scale.setScalar(radius*comp);r.point.scale.setScalar(radius*2.0*comp);r.dot.scale.setScalar((n.mastery==='mastered'?radius*3.6:n.mastery==='touched'?radius*2.65:radius*1.5)*comp);const selected=selectedId?byId.get(selectedId):undefined,related=selectedId===null||selectedId===n.id||n.premises.includes(selectedId)||Boolean(selected?.premises.includes(n.id));const pointMaterial=r.point.material as THREE.SpriteMaterial;pointMaterial.color.setHex(color);r.basePointOpacity=(n.status==='falsified'?.46:n.status==='suspended'?.55:n.status==='disputed'?.72:KNOWLEDGE_SCENE_THEME.node.pointOpacity)*(related?1:.35);pointMaterial.opacity=r.basePointOpacity;const dotMaterial=r.dot.material as THREE.SpriteMaterial;dotMaterial.map=n.mastery==='mastered'?strongTex:fluorTex;dotMaterial.color.setHex(KNOWLEDGE_SCENE_THEME.mastery.tint);r.baseDotOpacity=masteryOpacity(n)*(related?1:.45);dotMaterial.opacity=r.baseDotOpacity;const material=r.shell.material as THREE.MeshPhongMaterial;material.color.setHex(color);material.emissive.setHex(color);r.baseShellOpacity=(n.status==='falsified'?.18:n.status==='suspended'?.28:n.status==='disputed'?.46:KNOWLEDGE_SCENE_THEME.node.shellOpacity)*(related?1:.3);material.opacity=r.baseShellOpacity;material.emissiveIntensity=selectedId===n.id?KNOWLEDGE_SCENE_THEME.node.selectedEmissiveIntensity:KNOWLEDGE_SCENE_THEME.node.baseEmissiveIntensity;});const now=performance.now();if(!largeMobileGraph&&now-lastEdgeSync>=100){syncEdges(nodes);lastEdgeSync=now;}else if(largeMobileGraph)edgesGroup.visible=false;applyVisibility();};
 const applyPendingPulse=(time:number)=>{pendingNodeIds.forEach(id=>{const r=nodeMap[id];if(!r||!r.group.visible)return;const pulse=pendingPulseState(id,time);r.group.scale.setScalar(pulse.scale);(r.shell.material as THREE.MeshPhongMaterial).opacity=r.baseShellOpacity*pulse.opacityFactor;(r.point.material as THREE.SpriteMaterial).opacity=r.basePointOpacity*pulse.opacityFactor;(r.dot.material as THREE.SpriteMaterial).opacity=r.baseDotOpacity*pulse.opacityFactor;});};
 const physics=(dt:number)=>{const nodes=getNodes(),byId=new Map(nodes.map(n=>[n.id,n])),twins=new Map<string,KnowledgeSceneNode[]>(),inverseWorldRotation=worldGroup.quaternion.clone().invert();nodes.forEach(n=>{if(n.twinGroup)twins.set(n.twinGroup,[...(twins.get(n.twinGroup)??[]),n]);});nodes.forEach((n,index)=>{if(!hasFiniteCoordinates(n.pos))place(n);if(draggedNodeId===n.id)return;if(isCoreNodeId(n.id)){const i=SUN_TRIAD_IDS.indexOf(n.id as (typeof SUN_TRIAD_IDS)[number]),screenOrbit=coreOrbitScreenPosition(i,clock.elapsedTime*SUN_ANGULAR_SPEED);n.pos!.copy(screenOrbit.applyQuaternion(inverseWorldRotation));return;}n.vel??=new THREE.Vector3();n.homePos??=n.pos!.clone();n.vel.add(scratch.copy(n.homePos).sub(n.pos!).multiplyScalar(.02));const neighborCount=Math.min(nodes.length-1,32);for(let offset=1;offset<=neighborCount;offset++){const o=nodes[(index+offset)%nodes.length];if(!hasFiniteCoordinates(o.pos)||isCoreNodeId(o.id))continue;const d=scratch.copy(n.pos!).sub(o.pos!),d2=Math.max(d.lengthSq(),80);if(d.lengthSq()>1e-12)n.vel.add(d.normalize().multiplyScalar(12/d2));}[...n.premises,...(n.logicRuleId?[n.logicRuleId]:[])].forEach(pid=>{const p=byId.get(pid);if(p&&!isCoreNodeId(p.id)&&hasFiniteCoordinates(p.pos)){const d=scratch.copy(p.pos!).sub(n.pos!),len=d.length();if(len>0)n.vel!.add(d.normalize().multiplyScalar((len-TWIN_REST_LEN)*.0015));}});if(n.twinGroup){const t=twins.get(n.twinGroup)?.find(o=>o!==n&&hasFiniteCoordinates(o.pos));if(t?.pos){const d=scratch.copy(t.pos).sub(n.pos!);n.vel.add(d.multiplyScalar((d.length()-TWIN_REST_LEN)*.002));}}n.vel.multiplyScalar(.88);n.pos!.addScaledVector(n.vel,dt*60);if(!hasFiniteCoordinates(n.pos)||!hasFiniteCoordinates(n.vel))place(n);});};
 const labels=()=>{scene.updateMatrixWorld(true);const nodes=getNodes(),largeMobileGraph=mobilePerformance&&nodes.length>200;nodes.forEach((n,index)=>{const l=labelMap[n.id],r=nodeMap[n.id];if(!l||!r)return;r.group.getWorldPosition(worldPos);const s=worldPos.clone().project(camera),visible=r.group.visible&&(!largeMobileGraph||index%4===0||selectedId===n.id)&&s.z>-1&&s.z<1&&(!isCoreNodeId(n.id)||coreLabelsVisible(graphZoom));l.style.display=visible?'':'none';if(!visible)return;l.style.transform=`translate(-50%, -50%) translate(${(s.x*.5+.5)*host.clientWidth}px, ${(-s.y*.5+.5)*host.clientHeight}px)`;l.style.opacity=String(labelBrightness);l.classList.toggle('selected',selectedId===n.id);});};
 const pick=(x:number,y:number)=>{const rect=renderer.domElement.getBoundingClientRect();if(rect.width<=0||rect.height<=0)return null;const shells=Object.values(nodeMap).filter(record=>record.group.visible).map(record=>record.shell);if(mobilePerformance){let nearest:{id:string;distance:number}|null=null;for(const shell of shells){shell.parent!.getWorldPosition(worldPos);const projected=worldPos.clone().project(camera);if(!hasFiniteCoordinates(projected))continue;const sx=rect.left+(projected.x*.5+.5)*rect.width,sy=rect.top+(-projected.y*.5+.5)*rect.height,distance=Math.hypot(sx-x,sy-y),id=shell.parent?.userData.nodeId;if(typeof id==='string'&&distance<=24&&(!nearest||distance<nearest.distance))nearest={id,distance};}return nearest?.id??null;}ndc.set(((x-rect.left)/rect.width)*2-1,-(((y-rect.top)/rect.height)*2-1));raycaster.setFromCamera(ndc,camera);const hit=raycaster.intersectObjects(shells,false)[0]?.object.parent?.userData.nodeId;return typeof hit==='string'?hit:null;};
 const down=(e:PointerEvent)=>{if(overlayVisible)return;if(e.pointerType==='mouse')renderer.domElement.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});downX=lastX=e.clientX;downY=lastY=e.clientY;if(pointers.size===2){const[a,b]=[...pointers.values()];pinchStartDist=Math.hypot(a.x-b.x,a.y-b.y);pinchStartZoom=graphZoom;pinchOccurred=true;mode='pinch';return;}draggedNodeId=pick(e.clientX,e.clientY);mode=draggedNodeId?'node':'rotate';};
 const move=(e:PointerEvent)=>{if(overlayVisible)return;if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(mode==='pinch'&&pointers.size>=2){const[a,b]=[...pointers.values()],dist=Math.max(Math.hypot(a.x-b.x,a.y-b.y),1);graphZoom=clampGraphZoom(pinchStartZoom*dist/pinchStartDist);}else if(mode==='rotate'){worldGroup.rotation.y+=(e.clientX-lastX)*.004;worldGroup.rotation.x+=(e.clientY-lastY)*.004;}else if(mode==='node'&&draggedNodeId){const n=getNodes().find(v=>v.id===draggedNodeId);if(n?.pos){const d=new THREE.Vector3((e.clientX-lastX)*.45/graphZoom,-(e.clientY-lastY)*.45/graphZoom,0).applyQuaternion(worldGroup.quaternion.clone().invert());n.pos.add(d);}}lastX=e.clientX;lastY=e.clientY;};
 const up=(e:PointerEvent)=>{if(overlayVisible)return;performance.mark?.('knowledge-node-tap-start');pointers.delete(e.pointerId);if(renderer.domElement.hasPointerCapture(e.pointerId))renderer.domElement.releasePointerCapture(e.pointerId);const moved=Math.hypot(e.clientX-downX,e.clientY-downY)>6,nodeId=!moved&&!pinchOccurred?pick(e.clientX,e.clientY):null;if(nodeId){selectedId=nodeId;window.setTimeout(()=>callbacks.onNodeTap(nodeId),0);}else if(!moved&&!pinchOccurred){const now=performance.now();if(now-lastBgTapTime<280){if(bgTapTimer!==null)clearTimeout(bgTapTimer);bgTapTimer=null;callbacks.onBackgroundDoubleTap();}else bgTapTimer=window.setTimeout(()=>callbacks.onBackgroundTap(),280);lastBgTapTime=now;}if(pointers.size===0){mode=null;draggedNodeId=null;pinchOccurred=false;}performance.mark?.('knowledge-node-tap-end');performance.measure?.('knowledge-node-tap','knowledge-node-tap-start','knowledge-node-tap-end');};
 const wheel=(e:WheelEvent)=>{if(overlayVisible)return;e.preventDefault();graphZoom=clampGraphZoom(graphZoom*Math.exp(-e.deltaY*.0015));};
 const resize=()=>{camera.aspect=host.clientWidth/Math.max(host.clientHeight,1);camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight);document.documentElement.style.setProperty('--app-height',`${window.innerHeight}px`);};
 const scheduleFrame=()=>{if(!running||overlayVisible)return;const largeMobileGraph=mobilePerformance&&getNodes().length>200,delay=largeMobileGraph&&pendingNodeIds.size===0?100:0;if(delay)frameTimer=window.setTimeout(()=>{frameTimer=null;rafId=requestAnimationFrame(frame);},delay);else rafId=requestAnimationFrame(frame);};
 const frame=(time=performance.now())=>{if(!running||overlayVisible)return;const largeMobileGraph=mobilePerformance&&getNodes().length>200;if(mobilePerformance&&time-lastFrameAt<33){scheduleFrame();return;}lastFrameAt=time;if(largeMobileGraph&&!largeGraphDirty){if(pendingNodeIds.size>0){applyPendingPulse(time);renderer.render(scene,camera);}scheduleFrame();return;}const dt=Math.min(clock.getDelta(),.05);if(!largeMobileGraph)physics(dt);sync();applyPendingPulse(time);labels();renderer.render(scene,camera);largeGraphDirty=false;scheduleFrame();};
 const pauseFrameLoop=()=>{cancelAnimationFrame(rafId);rafId=0;if(frameTimer!==null)clearTimeout(frameTimer);frameTimer=null;};
 const resumeFrameLoop=()=>{if(!running||overlayVisible)return;clock.start();lastFrameAt=0;largeGraphDirty=true;frame();};
 renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',up);renderer.domElement.addEventListener('wheel',wheel,{passive:false});resize();
 return{markDirty:()=>{largeGraphDirty=true;},start:()=>{if(!running){running=true;resumeFrameLoop();}},stop:()=>{running=false;pauseFrameLoop();},setOverlayVisible:visible=>{if(overlayVisible===visible)return;overlayVisible=visible;labelsLayer.style.display=visible?'none':'block';if(visible)pauseFrameLoop();else resumeFrameLoop();},resize,setLabelBrightness:n=>{labelBrightness=THREE.MathUtils.clamp(n,.1,1);largeGraphDirty=true;},setNodeRadius:n=>{nodeRadiusMM=THREE.MathUtils.clamp(n,.1,30);largeGraphDirty=true;},setHideUntouched:e=>{hideUntouched=e;applyVisibility();largeGraphDirty=true;},setCascadeDepthLimit:()=>{},getCameraZ:()=>camera.position.z,screenPositionForNode:id=>{const record=nodeMap[id];if(!record)return null;record.group.getWorldPosition(worldPos);const projected=worldPos.clone().project(camera),rect=renderer.domElement.getBoundingClientRect();return hasFiniteCoordinates(projected)?{x:rect.left+(projected.x*.5+.5)*rect.width,y:rect.top+(-projected.y*.5+.5)*rect.height}:null;}};
}
