import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
const app=readFileSync('src/ui/app.ts','utf8');
const entry=readFileSync('src/ui/scene/UniformLayerLayout.ts','utf8');
const implementation=readFileSync('src/ui/scene/Deterministic5RLayout.ts','utf8');
assert(app.includes("import { applyUniformLayerLayout } from './scene/UniformLayerLayout';"));
assert(entry.includes("from './Deterministic5RLayout'"),'one narrow runtime layout owner remains');
assert(entry.includes("lineageRoleFor(node) !== 'rejected'"),'legacy rejected audit records must never enter runtime ISG');
assert(entry.includes('delete node.address')&&entry.includes('delete node.pos')&&entry.includes('delete node.homePos'),'legacy rejected records must not retain stale spatial authority');
assert(!existsSync('src/ui/scene/RadialKnowledgeLayout.ts'));
for(const forbidden of ['FccOccupancy','snapToNearestFcc','FCC_AXIS_STEP','fibonacciDirections','nearestFree','Math.random()'])assert(!implementation.includes(forbidden),`obsolete authority returned: ${forbidden}`);
assert(implementation.includes('generateIcosahedralGrid'));
assert(implementation.includes('address?: SpatialAddress'));
assert(implementation.includes('Inputs are mutated only after a complete component solution exists'));
assert(implementation.includes('for(const [id,address] of addresses)'),'authoritative node mutation occurs in one final commit after component searches');
assert(implementation.includes('countLayerCrossings(p,complete)'),'the bounded ISG search measures real relation crossings');
assert(implementation.includes('complex=metadata(g).sort(hardness)'),'complexity-first order remains authoritative');
assert(implementation.includes("ordered=[...complex.filter(c=>c.ids.length>1),...complex.filter(c=>c.ids.length===1)]"),'standalone nodes are placed last');
console.log('Single-owner Icosahedral Spherical Grid runtime architecture checks passed.');
