import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import './ShellExpansionRemap.test';
import './ReasoningRadialPlacement.test';
import './OrdinaryLineagePlacement.test';

const app=readFileSync('src/ui/app.ts','utf8');
const entry=readFileSync('src/ui/scene/UniformLayerLayout.ts','utf8');
const implementation=readFileSync('src/ui/scene/Deterministic5RLayout.ts','utf8');
const reasoningProjection=readFileSync('src/ui/scene/ReasoningRadialPlacement.ts','utf8');
const ordinaryLineageProjection=readFileSync('src/ui/scene/OrdinaryLineagePlacement.ts','utf8');
assert(app.includes("import { applyUniformLayerLayout } from './scene/UniformLayerLayout';"));
assert(entry.includes("from './Deterministic5RLayout'"),'one narrow global main-chain layout owner remains');
assert(entry.includes("from './ReasoningRadialPlacement'"),'runtime must retain the non-authoritative Reasoning projection after final ordinary Knowledge geometry');
assert(entry.includes("from './OrdinaryLineagePlacement'"),'ordinary Knowledge lineage must have its own local layout stage');
assert(entry.includes('const globalMainChain = spatialKnowledge.filter(node => !isOrdinaryLineageSatellite(node))'),'ordinary history/opposition/candidates are solved after Current rather than perturbing its initial global anchor');
assert(entry.indexOf('applyDeterministic5RLayout(globalMainChain)')<entry.indexOf('applyOrdinaryLineagePlacement(spatialKnowledge)'),'ordinary lineage must run only after the Current/main-chain anchor exists');
assert(entry.indexOf('applyOrdinaryLineagePlacement(spatialKnowledge)')<entry.indexOf('applyReasoningRadialPlacement(globalMainChain)'),'Reasoning projection must follow final ordinary Knowledge positions after any lineage-priority local reflow');
assert(ordinaryLineageProjection.includes('ORDINARY_LINEAGE_SPACING = LAYOUT_UNIT'),'ordinary lineage neighbour spacing must use the project 5R layout unit');
assert(ordinaryLineageProjection.includes('generateIcosahedralGrid'),'ordinary lineage must occupy the authoritative shell grid rather than free XYZ satellites');
assert(ordinaryLineageProjection.includes('node.address = { shellID, cellID }'),'ordinary lineage members must receive authoritative shellID/cellID occupancy');
assert(ordinaryLineageProjection.includes('grid.edges.has(edgeKey'),'ordinary lineage adjacency must follow an actual shell coordinate-line edge');
assert(ordinaryLineageProjection.includes('relocateOrdinaryBlockers'),'blocked lineage lines must locally re-layout ordinary blockers instead of failing or bending the lineage invariant');
assert(ordinaryLineageProjection.includes('protectedAnchorIds'),'other active lineage anchors remain hard occupancy during local reflow');
assert(ordinaryLineageProjection.includes("node.type === 'reasoning'"),'ordinary lineage logic must explicitly exclude Reasoning nodes');
assert(ordinaryLineageProjection.includes("role === 'history'")&&ordinaryLineageProjection.includes("role === 'opposition'"),'ordinary lineage owns history/opposition local geometry');
assert(reasoningProjection.includes('(meanRadius(premises) + meanRadius(conclusions)) * 0.5'),'Reasoning radius must be the midpoint of premise/conclusion shell radii');
assert(reasoningProjection.includes('conclusionAxis.normalize()'),'Reasoning direction must be owned by the conclusion radial axis');
assert(reasoningProjection.includes('delete reasoning.address'),'Reasoning projection must never create authoritative ISG occupancy');
assert(entry.includes("lineageRoleFor(node) !== 'rejected'"),'legacy rejected audit records must never enter runtime geometry');
assert(entry.includes('delete node.address')&&entry.includes('delete node.pos')&&entry.includes('delete node.homePos'),'legacy rejected records must not retain stale spatial authority');
assert(!existsSync('src/ui/scene/RadialKnowledgeLayout.ts'));
for(const forbidden of ['FccOccupancy','snapToNearestFcc','FCC_AXIS_STEP','fibonacciDirections','nearestFree','Math.random()','scoreState(placed','compareState(a:','DIRECTION_TRIAL_LIMIT','MAX_COMPONENT_EXPANSIONS','stableDirection(componentId','fixedCompactPlacement','NO_IMPROVEMENT_LIMIT'])assert(!implementation.includes(forbidden),`obsolete authority/objective returned: ${forbidden}`);
assert(implementation.includes('generateIcosahedralGrid'));
assert(implementation.includes('address?: SpatialAddress'));
assert(implementation.includes('Inputs are mutated only after a complete component solution exists'));
assert(implementation.includes('Atomic final commit: no input node is mutated'),'authoritative node mutation occurs only after the complete occupancy candidate passes');
assert(implementation.includes('realKnowledgeLineLength'),'chain scoring must use real Knowledge-to-Knowledge total line length');
assert(implementation.includes('PROJECTION_CANDIDATE_COUNT = 7'),'each next shell searches a bounded neighbourhood around the radial projection instead of owning one fixed cell');
assert(implementation.includes('targetForNode'),'already placed real neighbours define the next-shell radial projection target');
assert(implementation.includes('CANDIDATE_PATH_WIDTH'),'multiple nearby projected paths are retained before the shortest real line wins');
assert(implementation.includes('directionLevelDirections'),'direction authority is generated from recursive icosahedral subdivision levels');
assert(implementation.includes('return level===0?12:30*(4**(level-1))'),'direction levels grow without an arbitrary maximum: 12, +30, +120, +480 ...');
assert(implementation.includes('while((allocator.used.get(level)?.size??0)>=directionLevelDirections(level).length)level++'),'a finer angular level opens only when the current level is already full');
assert(implementation.includes('A component may expand outward, but it may not unlock a finer direction level'),'failed placement expands the whole component by 5R while retaining the same active angular level');
assert(implementation.includes('for(;;)'),'outward placement has no fixed expansion-count ceiling');
assert(implementation.includes('BALANCED_ICO_ORDER'),'the first twelve directions use one fixed balanced order');
assert(implementation.includes('componentDirectionLevels')&&implementation.includes('componentDirectionSlots'),'the authoritative run records which hierarchical direction slot each component owns');
assert(implementation.includes('Boundary expansion is not a new layout'),'shell expansion must use a separate fixed-direction remap path');
assert(implementation.includes('boundaryShiftFor'),'shell expansion must classify movement by whole component');
assert(implementation.includes("pureCyan=layers.every(layer=>layer==='inner')"),'Cyan/Blue expansion must leave only purely Cyan components fixed');
assert(implementation.includes("hasPurple=layers.some(layer=>layer==='outer')"),'Blue/Purple expansion must move every component containing Purple');
assert(implementation.includes('remapComponentOutward'),'existing chains must map from committed positions instead of being re-searched');
assert(implementation.includes('componentOptimizationPasses.set(c.id,0)'),'boundary-remapped chains must not rerun internal optimization');
assert(implementation.includes('directionSwitchCounts.set(c.id,0)'),'boundary-remapped chains must not search or switch direction');
assert(implementation.includes('Outward boundary remap invariant violated'),'an impossible outward collision is treated as an invariant failure, not as permission to rotate the chain');
assert(implementation.includes('placementsAreLegal(finalPlacements'),'occupancy is rebuilt and globally validated before commit');
assert(implementation.includes('restoreSpatialSnapshot'),'failed candidate construction restores the pre-run spatial state');
assert(implementation.includes('complex=metadata(g).sort(hardness)'),'complexity-first order remains authoritative for initial placement');
assert(implementation.includes("ordered=[...complex.filter(c=>c.ids.length>1),...complex.filter(c=>c.ids.length===1)]"),'standalone nodes are placed last during initial placement');
assert(implementation.includes('countLayerCrossings'));
assert(!implementation.includes('countLayerCrossings('+'path'),'crossing count must never score layout');
console.log('Single-owner hierarchical radial ISG runtime architecture checks passed.');
