import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
const app=readFileSync('src/ui/app.ts','utf8');
const entry=readFileSync('src/ui/scene/UniformLayerLayout.ts','utf8');
const implementation=readFileSync('src/ui/scene/Deterministic5RLayout.ts','utf8');
assert(app.includes("import { applyUniformLayerLayout } from './scene/UniformLayerLayout';"));
assert(entry.includes("from './Deterministic5RLayout'"),'one narrow runtime layout owner remains');
assert(entry.includes("lineageRoleFor(node) !== 'rejected'"),'legacy rejected audit records must never enter runtime ISG');
assert(entry.includes('delete node.address')&&entry.includes('delete node.pos')&&entry.includes('delete node.homePos'),'legacy rejected records must not retain stale spatial authority');
assert(!existsSync('src/ui/scene/RadialKnowledgeLayout.ts'));
for(const forbidden of ['FccOccupancy','snapToNearestFcc','FCC_AXIS_STEP','fibonacciDirections','nearestFree','Math.random()','BeamState','scoreState(placed','compareState(a:'])assert(!implementation.includes(forbidden),`obsolete authority/objective returned: ${forbidden}`);
assert(implementation.includes('generateIcosahedralGrid'));
assert(implementation.includes('address?: SpatialAddress'));
assert(implementation.includes('Inputs are mutated only after a complete component solution exists'));
assert(implementation.includes('for(const [id,address] of addresses)'),'authoritative node mutation occurs in one final commit after component searches');
assert(implementation.includes('realKnowledgeLineLength'),'chain optimization must use real Knowledge-to-Knowledge total line length');
assert(implementation.includes('mappedNeighborCenter'),'premises and conclusions must attract each other toward their mapped shell center');
assert(implementation.includes('NO_IMPROVEMENT_LIMIT = 5'),'five consecutive non-improving passes are the convergence rule');
assert(implementation.includes('fixedCompactPlacement'),'a chosen radial direction must own one fixed compact slot set per shell');
assert(implementation.includes('A blocked compact slot changes the whole chain direction'),'blocked target slots must rotate the component instead of falling through to farther cells');
assert(implementation.includes('Diagnostic utility only. Crossings are not an optimization objective.'),'crossing count may remain diagnostic but must not score layout');
assert(implementation.includes('complex=metadata(g).sort(hardness)'),'complexity-first order remains authoritative');
assert(implementation.includes("ordered=[...complex.filter(c=>c.ids.length>1),...complex.filter(c=>c.ids.length===1)]"),'standalone nodes are placed last');
console.log('Single-owner compact radial ISG runtime architecture checks passed.');
